name: LINE Cron Job

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render Cron
        run: |
          curl -X GET "https://linebot-rehab.onrender.com/"
